title: "House Price Prediction (Python)"
email: wphiri@beda.ie
description: "Portfolio project using Multiple Linear Regression in Python."
url: "https://kochezz.github.io"
baseurl: "/001-house-price-prediction-python"

remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

author:
  name: "William Phiri"
  avatar: "/assets/images/profile.png"
  bio: "Data Science Portfolio | Python & R | Business Enterprise Data Architecture (BEDA)"

# Optional: enable logo support in the theme
logo: "/assets/images/BEDA logo3.png"
